123
uliss4ever/111-Py pull request #1
Opened 2020-12-19 13:07 UTC by uliss4ever

Калинина Евгения
изменения внесены

2020-12-19 13:55 UTC, HeTop requested changes
1

2020-12-25 13:10 UTC, HeTop commented
Пишите, пожалуйста, в заголовке пулл реквеста название задания. 
Также, пишите свои вопросы не в коммите, а тут в сообщениях.

2020-12-25 13:15 UTC, HeTop requested changes

2020-12-25 13:15 UTC, HeTop commented on Tasks/a0_my_stack.py
> +    global my_stack
Что это такое???

2020-12-25 13:15 UTC, HeTop commented on Tasks/a0_my_stack.py
> +    if 0 <= ind < len(my_stack):
Какое-то очень странное условие. Зачем нужно сравнение с нулём?

2020-12-25 13:17 UTC, HeTop commented
Ваш вопрос в коммите не совсем понятно к какому заданию относится. Поясните его, пожалуйста.

2020-12-29 16:48 UTC, EnotYoyo commented on Tasks/a0_my_stack.py
> +    if 0 <= ind < len(my_stack):
А если подададут -100?

2021-01-03 08:51 UTC, closed without merging