Ffibb
uliss4ever/111-Py pull request #12
Opened 2021-01-10 11:58 UTC by uliss4ever

2021-01-10 20:38 UTC, EnotYoyo commented on Tasks/b0_linear_search.py
> +print(min_search([1,2,3,-4,5]))
Я рассказывал на практике под какую конструкцию надо прятать свой тестовый код, чтобы он не вызывался в тестах :)

2021-01-10 20:39 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        res += x**a/next(val)
Числитель можно было тоже эффективно вычислять (зная предыдущее значение)

2021-01-10 20:40 UTC, EnotYoyo commented on Tasks/c0_fib.py
> +    fib = [0] * (n + 2)
Не нужно хранить все элементы, достаточно двух последних

2021-01-10 20:42 UTC, EnotYoyo requested changes
В этом PR много разных изменений (причем часть явно не готовых). Не понял, что именно нужно посмотреть. 
Удалите из ветки лишние изменения.

2021-01-17 15:55 UTC, uliss4ever commented on Tasks/b0_linear_search.py
> +print(min_search([1,2,3,-4,5]))
@EnotYoyo 
ага, а если вызов просто стереть, всё равно эту штуку писать?

2021-01-17 17:04 UTC, uliss4ever commented on Tasks/c0_fib.py
> +    fib = [0] * (n + 2)
@EnotYoyo 
А что нужно поменять? Строчку просто так убрать не получилось, всё ломается(

2021-01-17 17:07 UTC, uliss4ever commented
> В этом PR много разных изменений (причем часть явно не готовых). Не понял, что именно нужно посмотреть.
> Удалите из ветки лишние изменения.

@EnotYoyo 
Я пыталась. Но локально у меня в ветке Фибоначчи только факториал, его откатила. А тут всё равно черти что. Извините) К Фибоначчи приписала коммент, его посмотреть. Если что - у меня пулреквесты называются так, как нужное задание, это единственное, что точно)

2021-01-19 18:11 UTC, EnotYoyo commented on Tasks/c0_fib.py
> +    fib = [0] * (n + 2)
Можно использовать не список, а просто две переменные.

2021-01-30 07:51 UTC, merged