My prior queue
uliss4ever/111-Py pull request #3
Opened 2020-12-29 16:37 UTC by uliss4ever

Очередь с приоритетами

2020-12-29 18:26 UTC, EnotYoyo requested changes
Доделайте задание со скобочками

2020-12-29 18:26 UTC, EnotYoyo commented on Tasks/a0_my_stack.py
> +    print("!")
Явно случайно сюда попал, удалите )

2020-12-29 18:26 UTC, EnotYoyo commented on Tasks/a1_my_queue.py
> +        print(-ind-1)
Этот принт не будет работать, поскольку перед ним всегда return

2020-12-29 18:26 UTC, EnotYoyo commented on Tasks/a3_check_brackets.py
> +    print(a)
Тут идея правильная, но почему то недоделанная до конца.

2021-01-03 08:20 UTC, uliss4ever commented on Tasks/a0_my_stack.py
> +    print("!")
Андрей Александрович, я правильно сделала, что удалила его в локальной ветке my_queue в файле my_stack ? (Потому что я его там нашла, а не в ветке my_stack)

2021-01-04 19:28 UTC, closed without merging